### ISSUE TITLE
Extraction bug

### ISSUE THREAD

**Issue by DSblizzard** [bwbaugh/wikipedia-extractor#1]
Article http://en.wikipedia.org/wiki/Alabama have following text:
"At 1,300 miles (2,100 km), Alabama has one of the longest navigable inland waterways in the nation"
which extracted as follows:
At , Alabama has one of the longest navigable inland waterways in the nation.

**Comment by hayounav** [comment]
I assume that since the issue was opened almost 1.5 years ago, this is no longer relevant to the OP. However, I'll leave this here in case someone else has this problem.

This is not really an issue. It happens because the markup for that sentence is "At {{convert|1300|mi|km}}, Alabama has one of the longest navigable inland waterways in the nation." and the wikipedia-extractor just ignores all template markup (since it is not a wikipedia markup parser, but rather a text extractor).

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
