### ISSUE TITLE
Invalid syntax error when running

### ISSUE THREAD

**Issue by Lolologist** [bwbaugh/wikipedia-extractor#15]
python WikiExtractor.py -cb 250K -o extracted itwiki-20150316-pages-articles1.xml.bz2 
  File "WikiExtractor.py", line 860
    afterPat = { o:re.compile(openPat+'|'+c, re.DOTALL) for o,c in izip(openDelim, closeDelim)}
                                                          ^
SyntaxError: invalid syntax

On latest version, running 2.6.6 on CentOS 6
Of note, it does then when given no arguments or -h or anything as well.

**Comment by bwbaugh** [comment]
This is a mirror repo (mainly for history before the author moved to github).

If the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor

---

With that said, the issue appears to be that the script only supports Python 2.7 and above.
