### ISSUE TITLE
Version 2.8 dead loops on "Reached max template recursion"

### ISSUE THREAD

**Issue by ghost** [bwbaugh/wikipedia-extractor#6]
I tried version 2.8 on latest full wikipedia english dump. If "Reached max template recursion" is triggered by one page, this warning may propagate to the following pages. Most of the time, the extractor dead loops forever until it's killed by OS.

**Comment by dirkgr** [comment]
Same problem here.

**Comment by wimmuskee** [comment]
This Github page only mirrors the code and, as far as I know, is not from the Wikipedia-Extractor guys themselves. 
The best thing you can do is mail the authors (listed in script) directly.

**Comment by dirkgr** [comment]
I believe the original author is here: https://github.com/attardi/wikiextractor.

**Comment by bwbaugh** [comment]
As mentioned above, this is a mirror repo (mainly for history before the author moved to github).

It looks like this might have already been solved due to the linked issues. However if the issue is still outstanding, please consider making an issue on the official repo: https://github.com/attardi/wikiextractor
